### ISSUE TITLE
try-with-resources文を使ってみませんか？

### ISSUE THREAD

**Issue by SasakiU** [CentralsoftTrain2018/kakeibo#10]
https://github.com/CentralsoftTrain2018/kakeibo/blob/master/src/dao/ConanDao.java
ConanDao.java L43～L78 SQL実行まわり

PreparedStatementクラスはAutoCloseableインターフェースを実装しています。
ということは・・・
もう一つのグループの
https://github.com/CentralsoftTrain2018/OchisCode/blob/master/src/dao/UserClothDao.java
UserClothDao.java L39～L59
のようにtry-with-resources文を使うことでコンパクトに書けると思います。

~~ちなみに、PreparedStatementのcloseをきちんと行っていれば、ResultSetのcloseはやらなくてもいいです。~~
~~余裕があればこの理由について調べてみてください。~~
closeされるされないどちらにせよ、コードを見てcloseしなくていいのかなと疑問に思うので、
ResultSetについてもtry-with-resourcesで囲った方が完結していて良いと思います。

**Comment by tamagodaisukichan** [comment]
全てのDaoにtry-with-resources文を使用しました。
