### ISSUE TITLE
JavaDocコメント書きませんか？

### ISSUE THREAD

**Issue by kay77** [CentralsoftTrain2018/kakeibo#15]
https://github.com/CentralsoftTrain2018/kakeibo/blob/f79cc61ba8a180b6d0a1887ab6b5973a96e3952c/src/servlet/LoginServlet.java#L21

この箇所に限らずですが、JavaDocコメント書きませんか？
クラス、属性、メソッドの概要を入れておくだけで可読性はぐっと上がります。
ステップコメントをマメに入れるよりよっぽど効果的です。

簡単で構いません。
何を目的としどんな責務のクラスなのかをみんなで共有するためにも
JavaDocコメントを書いてみませんか？

参考
https://qiita.com/maku77/items/6410c67ce95e08d8d1bd
http://wa3.i-3-i.info/word15010.html

**Comment by essences** [comment]
すいません。

今回のスコープからはずしています。
いちおう学習させます。
