### ISSUE TITLE
コナンくんの言葉をJSPに持っていく

### ISSUE THREAD

**Issue by koni1212** [CentralsoftTrain2018/kakeibo#2]
https://github.com/CentralsoftTrain2018/kakeibo/blob/master/src/bean/ConanBean.java
ConanBean.java：43行
https://github.com/CentralsoftTrain2018/kakeibo/blob/master/src/bean/ConanListBean.java
ConanListBean.java：55～57行
コナンくんの言葉をBeanのtoStringに定義していますが、JSPで組み立てる方が望ましいです。
JSPを見ただけでどのような画面なのか分かる方が可読性が上がり、デザインを見直す際にも修正が効きやすくなります。
特にJavaに\<br\>などのHTMLタグをもたせていることで、デザインとロジックの分離ができずに密に関連するものになってしまっています。

**Comment by tamagodaisukichan** [comment]
コナンくんからの言葉をJSPに記述するよう修正しました。
