### ISSUE TITLE
参照されないArrayListをnewしている個所があります

### ISSUE THREAD

**Issue by SasakiU** [CentralsoftTrain2018/kakeibo#20]
https://github.com/CentralsoftTrain2018/kakeibo/blob/master/src/service/ExpenseService.java#L79
ExpenseService L79
```
List<CategoryVo> categoryList = new ArrayList<CategoryVo>();
categoryList = ExpenseDBManager.getCategory();
```
は
```
List<CategoryVo> categoryList = ExpenseDBManager.getCategory();
```
で良いと思います。

無駄にnewしてもメモリ的に良いことはないと思うので、
時間があれば修正お願いします。

さらにまとめて
```
eb.setCategoryList(ExpenseDBManager.getCategory());
```
としても良さそうですが、無駄なNewが無くなっているという意味では同じなので好きな方とってください。

**Comment by tamagodaisukichan** [comment]
前者の方法で修正しました。
ご指摘ありがとうございます。
