### ISSUE TITLE
VOにセッターがありますが、意図して作成していますか？

### ISSUE THREAD

**Issue by SasakiU** [CentralsoftTrain2018/kakeibo#21]
VOは不変オブジェクトだと思っていたのですが、
（可変にする場合は新たなオブジェクトを作り返却するようにする。Stringのように。）
セッターを用意して可変にしている意図があったら教えてください。
（DDDの可変のエンティティが無しのVOだけだから可変にしているとかでしょうか？）

ちなみに、VOを不変オブジェクトにする意味に気付いた、という記事がありました。
http://masuda220.jugem.jp/?eid=308

**Comment by essences** [comment]
DDDのVOのコンセプトとは違うものなので不変ではないんです

**Comment by SasakiU** [comment]
回答ありがとうございます。
