### ISSUE TITLE
StringBuffer :+1:

### ISSUE THREAD

**Issue by SasakiU** [CentralsoftTrain2018/kakeibo#22]
https://github.com/CentralsoftTrain2018/kakeibo/blob/master/src/vo/MokuhyouVo.java#L89
MokuhyouVo L89

StringBuffer使えていて :+1:

自分は現場での指摘でStringBuilderを使うように言われました。
StringBufferとStringBuilderの違いについて気になったのでちょっと調べてみました。

StringBuffer：スレッドセーフ　だからほんのわずか遅い
StringBuilder：スレッドセーフではない　だからほんのわずか速い

今回の使用箇所だと、このインスタンスをマルチスレッドで参照することはないと思うのでStringBuilderのほうが本当に微々たる差ですが良さそうです。

とはいえ、自分が現場で習ったことを研修ですでに使えていていいなと思いました。

**Comment by tamagodaisukichan** [comment]
MokuhyouVoはEclipceの自動生成機能で作成したオブジェクトなので、
StringBufferもEclipceで生成したものです。
実際に使用してはいませんが、新たな知識を学ぶことができました。ありがとうございます。
