### ISSUE TITLE
開発しているEclipseはAll in Oneではない？

### ISSUE THREAD

**Issue by koni1212** [CentralsoftTrain2018/kakeibo#28]
![image](https://user-images.githubusercontent.com/27844139/41607263-98389e30-7420-11e8-9709-d3e0718f7c78.png)
![image](https://user-images.githubusercontent.com/27844139/41607412-f1980772-7420-11e8-8dca-b43f4dc20cd8.png)

例えば私はEclipseのPleiades All in Oneを使っているのですが、保存とするだけでコードフォーマットが働くようにすでに設定されています。
開発しているEclipseはAll in Oneではないのですか？
中括弧の位置などが揃っていないものが見られました。

**Comment by essences** [comment]
こちらでは、Pleiades All in One の4.7をつかっています。　デフォルトではそのような機能はONになっていなかったです。

**Comment by essences** [comment]
来年度から考慮しますね。
ありがとうございます。
