### ISSUE TITLE
プロダクトオーナーの言葉をどこまで実装するの？

### ISSUE THREAD

**Issue by koni1212** [CentralsoftTrain2018/kakeibo#3]
https://central-soft.atlassian.net/wiki/spaces/Initialtraining/pages/305922196
プロダクトオーナーからの説明で以下のものが上がっていましたが、開発側から質問などは出ていませんでした。これらの要望はすべて仕様として取り入れるのでしょうか？
- 円グラフを表示する
- クーポンをQRコード表示する
- 家計簿の入力が面倒な人用にレシートの読み込みをする

**Comment by essences** [comment]
> 円グラフを表示する
やるつもりです。

> クーポンをQRコード表示する
やるつもりです。

> 家計簿の入力が面倒な人用にレシートの読み込みをする
規模がおおきすぎかつ優先順位が低いので、今回は実質やらない方向です。

**Comment by koni1212** [comment]
そうなのですね。どれも研修で学んでほしい内容からちょっと外へ出ていて見せかけ(固定の画像表示)などで済ませるものかと思いましたが、頑張ってください。楽しみにしています。
円グラフは外部のJavaScriptライブラリ使えばってかんじでしょうかね。
よみうりランドのバンジーで使えるクーポンの生成＋メール送信・・・スポンサー契約を取る程度の難易度ですね＞＜
