### ISSUE TITLE
【質問】分析画面で目標金額を超えたときにコナン君が言うカテゴリについて

### ISSUE THREAD

**Issue by SasakiU** [CentralsoftTrain2018/kakeibo#49]
分析画面で目標金額を超えたときにコナン君が目標を超えそうなカテゴリをアドバイスすると思いますが、
支出が0円の項目に対して、コナン君が出費を抑えてと言います。

目標に近づいている項目に対して、出費を抑えてと言ってくるのかなと思っていたのですが、
理解が違っていたでしょうか？

**Comment by ochi9y** [comment]
仕様です。コナン君がアドバイスする内容は超えそうなカテゴリを教えてたいのではなく、全体の目標を超えないようにどこの項目を抑えたほうが良いかを表示したいからです。

**Comment by SasakiU** [comment]
ありがとうございます。

確かに、どこかの項目が目標超えているのにほかの項目で抑えずに目標まで使ってしまったらトータル赤字になってしまいますね。
こういう「まだ何にも使ってないんだから使わせろ」みたいな考えの金遣いの荒い人でもコナン君のアドバイス通りにやっていけば貯金とかできそうですね！
