### ISSUE TITLE
DAO系、同様の役割に同じ属性ということは・・・

### ISSUE THREAD

**Issue by matap1623** [CentralsoftTrain2018/kakeibo#6]
DAO系ですが、皆 DBコネクション を属性にもっていますよね。

同様の役割(DBアクセスするため)のクラス達が皆同じ属性を持っている・・・
同様の役割のクラス に 同じ属性・・・

設計の工夫ができそうだぞ・・・

**Comment by ochi9y** [comment]
Daoを作成し親クラスにしました。
